version: '2'
services:
  proxy_pool:
    build: .
    container_name: proxy_pool
    ports:
      - "25010:5010"
    links:
      - proxy_redis
    environment:
      DB_CONN: "redis://@proxy_redis:6379/0"
    depends_on:
      - proxy_redis
  proxy_redis:
    image: "redis"
    container_name: proxy_redis
    volumes:
      - ./redis_data:/data
  proxy_flaresolverr:
    image: "ghcr.io/flaresolverr/flaresolverr:latest"
    container_name: proxy_flaresolverr
